name: Run Ansible

on:
  workflow_dispatch:
  push:

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: ec2_deploy.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, encrypted vault password
          vault_password: ${{secrets.VAULT_PASSWORD}}

